<dec f='codebrowser/src/mpack/mpack-common.h' l='275' type='union (anonymous union at /var/data/dev/source/active/vrtql/client/src/mpack/mpack-common.h:252:5)'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='309' u='m' c='mpack_tag_make_bool'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='317' u='m' c='mpack_tag_make_true'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='325' u='m' c='mpack_tag_make_false'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='333' u='m' c='mpack_tag_make_int'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='341' u='m' c='mpack_tag_make_uint'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='355' u='m' c='mpack_tag_make_float'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='369' u='m' c='mpack_tag_make_double'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='377' u='m' c='mpack_tag_make_array'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='385' u='m' c='mpack_tag_make_map'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='393' u='m' c='mpack_tag_make_str'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='401' u='m' c='mpack_tag_make_bin'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='445' u='m' c='mpack_tag_bool_value'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='463' u='m' c='mpack_tag_int_value'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='481' u='m' c='mpack_tag_uint_value'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='503' u='m' c='mpack_tag_float_value'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='525' u='m' c='mpack_tag_double_value'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='538' u='m' c='mpack_tag_array_count'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='551' u='m' c='mpack_tag_map_count'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='564' u='m' c='mpack_tag_str_length'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='577' u='m' c='mpack_tag_bin_length'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='631' u='m' c='mpack_tag_bytes'/>
<offset>64</offset>
<doc f='codebrowser/src/mpack/mpack-common.h' l='251'>/* The value for non-compound types. */</doc>
<use f='codebrowser/src/mpack/mpack-common.c' l='83' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='85' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='85' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='87' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='89' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='89' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='101' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='101' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='104' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='104' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='106' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='106' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='109' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='109' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='111' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='111' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='115' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='115' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='117' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='117' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='121' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='121' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='123' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='123' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='147' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='147' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='147' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='149' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='149' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='149' u='m' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='79' u='m' c='mpack_expect_u8'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='80' u='m' c='mpack_expect_u8'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='82' u='m' c='mpack_expect_u8'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='82' u='m' c='mpack_expect_u8'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='83' u='m' c='mpack_expect_u8'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='92' u='m' c='mpack_expect_u16'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='93' u='m' c='mpack_expect_u16'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='95' u='m' c='mpack_expect_u16'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='95' u='m' c='mpack_expect_u16'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='96' u='m' c='mpack_expect_u16'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='105' u='m' c='mpack_expect_u32'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='106' u='m' c='mpack_expect_u32'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='108' u='m' c='mpack_expect_u32'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='108' u='m' c='mpack_expect_u32'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='109' u='m' c='mpack_expect_u32'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='118' u='m' c='mpack_expect_u64'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='120' u='m' c='mpack_expect_u64'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='121' u='m' c='mpack_expect_u64'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='130' u='m' c='mpack_expect_i8'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='131' u='m' c='mpack_expect_i8'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='133' u='m' c='mpack_expect_i8'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='133' u='m' c='mpack_expect_i8'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='134' u='m' c='mpack_expect_i8'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='143' u='m' c='mpack_expect_i16'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='144' u='m' c='mpack_expect_i16'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='146' u='m' c='mpack_expect_i16'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='146' u='m' c='mpack_expect_i16'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='147' u='m' c='mpack_expect_i16'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='156' u='m' c='mpack_expect_i32'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='157' u='m' c='mpack_expect_i32'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='159' u='m' c='mpack_expect_i32'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='159' u='m' c='mpack_expect_i32'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='160' u='m' c='mpack_expect_i32'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='169' u='m' c='mpack_expect_i64'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='170' u='m' c='mpack_expect_i64'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='172' u='m' c='mpack_expect_i64'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='182' u='m' c='mpack_expect_float'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='184' u='m' c='mpack_expect_float'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='186' u='m' c='mpack_expect_float'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='190' u='m' c='mpack_expect_float'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='205' u='m' c='mpack_expect_double'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='207' u='m' c='mpack_expect_double'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='209' u='m' c='mpack_expect_double'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='211' u='m' c='mpack_expect_double'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='221' u='m' c='mpack_expect_float_strict'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='231' u='m' c='mpack_expect_double_strict'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='233' u='m' c='mpack_expect_double_strict'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='372' u='m' c='mpack_expect_map'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='391' u='m' c='mpack_expect_map_or_nil'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='414' u='m' c='mpack_expect_array'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='433' u='m' c='mpack_expect_array_or_nil'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='558' u='m' c='mpack_expect_bin'/>
<use f='codebrowser/src/mpack/mpack-node.c' l='1268' u='m' c='mpack_node_tag'/>
<use f='codebrowser/src/mpack/mpack-node.c' l='1269' u='m' c='mpack_node_tag'/>
<use f='codebrowser/src/mpack/mpack-node.c' l='1270' u='m' c='mpack_node_tag'/>
<use f='codebrowser/src/mpack/mpack-node.c' l='1271' u='m' c='mpack_node_tag'/>
<use f='codebrowser/src/mpack/mpack-node.c' l='1272' u='m' c='mpack_node_tag'/>
<use f='codebrowser/src/mpack/mpack-node.c' l='1274' u='m' c='mpack_node_tag'/>
<use f='codebrowser/src/mpack/mpack-node.c' l='1275' u='m' c='mpack_node_tag'/>
<use f='codebrowser/src/mpack/mpack-node.c' l='1284' u='m' c='mpack_node_tag'/>
<use f='codebrowser/src/mpack/mpack-node.c' l='1285' u='m' c='mpack_node_tag'/>
<use f='codebrowser/src/mpack/mpack-reader.c' l='997' u='m' c='mpack_discard'/>
<use f='codebrowser/src/mpack/mpack-reader.c' l='1001' u='m' c='mpack_discard'/>
<use f='codebrowser/src/mpack/mpack-reader.c' l='1011' u='m' c='mpack_discard'/>
<use f='codebrowser/src/mpack/mpack-reader.c' l='1011' u='m' c='mpack_discard'/>
<use f='codebrowser/src/mpack/mpack-reader.c' l='1020' u='m' c='mpack_discard'/>
<use f='codebrowser/src/mpack/mpack-reader.c' l='1020' u='m' c='mpack_discard'/>
<use f='codebrowser/src/mpack/mpack-writer.c' l='600' u='m' c='mpack_write_tag'/>
<use f='codebrowser/src/mpack/mpack-writer.c' l='601' u='m' c='mpack_write_tag'/>
<use f='codebrowser/src/mpack/mpack-writer.c' l='602' u='m' c='mpack_write_tag'/>
<use f='codebrowser/src/mpack/mpack-writer.c' l='610' u='m' c='mpack_write_tag'/>
<use f='codebrowser/src/mpack/mpack-writer.c' l='618' u='m' c='mpack_write_tag'/>
<use f='codebrowser/src/mpack/mpack-writer.c' l='621' u='m' c='mpack_write_tag'/>
<use f='codebrowser/src/mpack/mpack-writer.c' l='622' u='m' c='mpack_write_tag'/>
<use f='codebrowser/src/mpack/mpack-writer.c' l='630' u='m' c='mpack_write_tag'/>
<use f='codebrowser/src/mpack/mpack-writer.c' l='631' u='m' c='mpack_write_tag'/>
