<dec f='codebrowser/src/server.h' l='134' type='vrtql_http_req *'/>
<use f='codebrowser/src/server.c' l='1155' u='w' c='svr_cnx_new'/>
<use f='codebrowser/src/server.c' l='1164' u='r' c='svr_cnx_free'/>
<use f='codebrowser/src/server.c' l='1166' u='r' c='svr_cnx_free'/>
<use f='codebrowser/src/server.c' l='1527' u='r' c='ws_svr_client_read'/>
<use f='codebrowser/src/server.c' l='1530' u='r' c='ws_svr_client_read'/>
<use f='codebrowser/src/server.c' l='1533' u='r' c='ws_svr_client_read'/>
<use f='codebrowser/src/server.c' l='1555' u='r' c='ws_svr_client_read'/>
<use f='codebrowser/src/server.c' l='1598' u='r' c='ws_svr_client_read'/>
<use f='codebrowser/src/server.c' l='1599' u='w' c='ws_svr_client_read'/>
<offset>128</offset>
<doc f='codebrowser/src/server.h' l='133'>/* Flag holds the HTTP request that started connection. */</doc>
