<dec f='codebrowser/src/server.h' l='134' type='vws_http_msg *'/>
<use f='codebrowser/src/server.c' l='1167' u='w' c='svr_cnx_new'/>
<use f='codebrowser/src/server.c' l='1176' u='r' c='svr_cnx_free'/>
<use f='codebrowser/src/server.c' l='1178' u='r' c='svr_cnx_free'/>
<use f='codebrowser/src/server.c' l='1559' u='r' c='ws_svr_client_read'/>
<use f='codebrowser/src/server.c' l='1562' u='r' c='ws_svr_client_read'/>
<use f='codebrowser/src/server.c' l='1565' u='r' c='ws_svr_client_read'/>
<use f='codebrowser/src/server.c' l='1587' u='r' c='ws_svr_client_read'/>
<use f='codebrowser/src/server.c' l='1630' u='r' c='ws_svr_client_read'/>
<use f='codebrowser/src/server.c' l='1631' u='w' c='ws_svr_client_read'/>
<offset>128</offset>
<doc f='codebrowser/src/server.h' l='133'>/* Flag holds the HTTP request that started connection. */</doc>
