<dec f='codebrowser/src/server.h' l='278' type='vws_http_msg *'/>
<use f='codebrowser/src/server.c' l='1385' u='w' c='svr_cnx_new'/>
<use f='codebrowser/src/server.c' l='1397' u='r' c='svr_cnx_free'/>
<use f='codebrowser/src/server.c' l='1399' u='r' c='svr_cnx_free'/>
<use f='codebrowser/src/server.c' l='1874' u='r' c='ws_svr_client_read'/>
<use f='codebrowser/src/server.c' l='1877' u='r' c='ws_svr_client_read'/>
<use f='codebrowser/src/server.c' l='1880' u='r' c='ws_svr_client_read'/>
<use f='codebrowser/src/server.c' l='1887' u='r' c='ws_svr_client_read'/>
<use f='codebrowser/src/server.c' l='1902' u='r' c='ws_svr_client_read'/>
<use f='codebrowser/src/server.c' l='1944' u='r' c='ws_svr_client_read'/>
<use f='codebrowser/src/server.c' l='1945' u='w' c='ws_svr_client_read'/>
<offset>128</offset>
<doc f='codebrowser/src/server.h' l='277'>/* Flag holds the HTTP request that started connection. */</doc>
