<dec f='codebrowser/src/test/util/mongoose.h' l='987' type='int (*)(const char *, size_t *, time_t *)'/>
<offset>0</offset>
<doc f='codebrowser/src/test/util/mongoose.h' l='987'>// stat file</doc>
<use f='codebrowser/src/test/util/mongoose.c' l='29' u='r' c='mg_file_read'/>
<use f='codebrowser/src/test/util/mongoose.c' l='552' u='r' c='mg_http_serve_file'/>
<use f='codebrowser/src/test/util/mongoose.c' l='629' u='r' c='printdirentry'/>
<use f='codebrowser/src/test/util/mongoose.c' l='740' u='r' c='uri_to_path2'/>
<use f='codebrowser/src/test/util/mongoose.c' l='757' u='r' c='uri_to_path2'/>
<use f='codebrowser/src/test/util/mongoose.c' l='759' u='r' c='uri_to_path2'/>
<use f='codebrowser/src/test/util/mongoose.c' l='763' u='r' c='uri_to_path2'/>
<use f='codebrowser/src/test/util/mongoose.c' l='891' u='r' c='mg_http_upload'/>
