<dec f='codebrowser/src/mpack/mpack-common.h' l='270' type='uint32_t'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='393' u='w' c='mpack_tag_make_str'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='401' u='w' c='mpack_tag_make_bin'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='564' u='r' c='mpack_tag_str_length'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='577' u='r' c='mpack_tag_bin_length'/>
<use f='codebrowser/src/mpack/mpack-common.h' l='631' u='r' c='mpack_tag_bytes'/>
<offset>0</offset>
<doc f='codebrowser/src/mpack/mpack-common.h' l='269'>/* The number of bytes if the type is str, bin or ext. */</doc>
<use f='codebrowser/src/mpack/mpack-common.c' l='121' u='r' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='121' u='r' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='123' u='r' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-common.c' l='123' u='r' c='mpack_tag_cmp'/>
<use f='codebrowser/src/mpack/mpack-expect.c' l='558' u='r' c='mpack_expect_bin'/>
<use f='codebrowser/src/mpack/mpack-node.c' l='1274' u='w' c='mpack_node_tag'/>
<use f='codebrowser/src/mpack/mpack-node.c' l='1275' u='w' c='mpack_node_tag'/>
<use f='codebrowser/src/mpack/mpack-reader.c' l='997' u='r' c='mpack_discard'/>
<use f='codebrowser/src/mpack/mpack-reader.c' l='1001' u='r' c='mpack_discard'/>
<use f='codebrowser/src/mpack/mpack-writer.c' l='621' u='r' c='mpack_write_tag'/>
<use f='codebrowser/src/mpack/mpack-writer.c' l='622' u='r' c='mpack_write_tag'/>
