<dec f='include/openssl/pkcs7.h' l='114' type='unsigned char *'/>
<offset>0</offset>
<doc f='include/openssl/pkcs7.h' l='110'>/*
     * The following is non NULL if it contains ASN1 encoding of this
     * structure
     */</doc>
