<dec f='codebrowser/src/server.h' l='349' type='vrtql_http_req *'/>
<use f='codebrowser/src/server.c' l='1388' u='r' c='msg_svr_client_data_in'/>
<use f='codebrowser/src/server.c' l='1391' u='r' c='msg_svr_client_data_in'/>
<use f='codebrowser/src/server.c' l='1394' u='r' c='msg_svr_client_data_in'/>
<use f='codebrowser/src/server.c' l='1423' u='r' c='msg_svr_client_data_in'/>
<use f='codebrowser/src/server.c' l='1466' u='r' c='msg_svr_client_data_in'/>
<use f='codebrowser/src/server.c' l='1467' u='w' c='msg_svr_client_data_in'/>
<use f='codebrowser/src/server.c' l='1592' u='w' c='vrtql_msg_svr_new'/>
<use f='codebrowser/src/server.c' l='1612' u='r' c='vrtql_msg_svr_free'/>
<use f='codebrowser/src/server.c' l='1614' u='r' c='vrtql_msg_svr_free'/>
<offset>4480</offset>
<doc f='codebrowser/src/server.h' l='348'>/* Flag holds the HTTP request that started connection. */</doc>
