<dec f='codebrowser/src/util/yyjson.h' l='5154' type='uint64_t'/>
<use f='codebrowser/src/util/yyjson.h' l='5499' u='w' c='yyjson_mut_rawn'/>
<use f='codebrowser/src/util/yyjson.h' l='5520' u='w' c='yyjson_mut_rawncpy'/>
<use f='codebrowser/src/util/yyjson.h' l='5532' u='w' c='yyjson_mut_null'/>
<use f='codebrowser/src/util/yyjson.h' l='5543' u='w' c='yyjson_mut_true'/>
<use f='codebrowser/src/util/yyjson.h' l='5554' u='w' c='yyjson_mut_false'/>
<use f='codebrowser/src/util/yyjson.h' l='5566' u='w' c='yyjson_mut_bool'/>
<use f='codebrowser/src/util/yyjson.h' l='5578' u='w' c='yyjson_mut_uint'/>
<use f='codebrowser/src/util/yyjson.h' l='5591' u='w' c='yyjson_mut_sint'/>
<use f='codebrowser/src/util/yyjson.h' l='5609' u='w' c='yyjson_mut_real'/>
<use f='codebrowser/src/util/yyjson.h' l='5625' u='w' c='yyjson_mut_str'/>
<use f='codebrowser/src/util/yyjson.h' l='5640' u='w' c='yyjson_mut_strn'/>
<use f='codebrowser/src/util/yyjson.h' l='5657' u='w' c='yyjson_mut_strcpy'/>
<use f='codebrowser/src/util/yyjson.h' l='5673' u='w' c='yyjson_mut_strncpy'/>
<use f='codebrowser/src/util/yyjson.h' l='5787' u='w' c='yyjson_mut_arr'/>
<use f='codebrowser/src/util/yyjson.h' l='5799' u='w' c='yyjson_mut_arr_with_bool'/>
<use f='codebrowser/src/util/yyjson.h' l='5818' u='w' c='yyjson_mut_arr_with_bool'/>
<use f='codebrowser/src/util/yyjson.h' l='5799' u='w' c='yyjson_mut_arr_with_sint8'/>
<use f='codebrowser/src/util/yyjson.h' l='5840' u='w' c='yyjson_mut_arr_with_sint8'/>
<use f='codebrowser/src/util/yyjson.h' l='5799' u='w' c='yyjson_mut_arr_with_sint16'/>
<use f='codebrowser/src/util/yyjson.h' l='5848' u='w' c='yyjson_mut_arr_with_sint16'/>
<use f='codebrowser/src/util/yyjson.h' l='5799' u='w' c='yyjson_mut_arr_with_sint32'/>
<use f='codebrowser/src/util/yyjson.h' l='5856' u='w' c='yyjson_mut_arr_with_sint32'/>
<use f='codebrowser/src/util/yyjson.h' l='5799' u='w' c='yyjson_mut_arr_with_sint64'/>
<use f='codebrowser/src/util/yyjson.h' l='5864' u='w' c='yyjson_mut_arr_with_sint64'/>
<use f='codebrowser/src/util/yyjson.h' l='5799' u='w' c='yyjson_mut_arr_with_uint8'/>
<use f='codebrowser/src/util/yyjson.h' l='5872' u='w' c='yyjson_mut_arr_with_uint8'/>
<use f='codebrowser/src/util/yyjson.h' l='5799' u='w' c='yyjson_mut_arr_with_uint16'/>
<use f='codebrowser/src/util/yyjson.h' l='5880' u='w' c='yyjson_mut_arr_with_uint16'/>
<use f='codebrowser/src/util/yyjson.h' l='5799' u='w' c='yyjson_mut_arr_with_uint32'/>
<use f='codebrowser/src/util/yyjson.h' l='5888' u='w' c='yyjson_mut_arr_with_uint32'/>
<use f='codebrowser/src/util/yyjson.h' l='5799' u='w' c='yyjson_mut_arr_with_uint64'/>
<use f='codebrowser/src/util/yyjson.h' l='5896' u='w' c='yyjson_mut_arr_with_uint64'/>
<use f='codebrowser/src/util/yyjson.h' l='5799' u='w' c='yyjson_mut_arr_with_float'/>
<use f='codebrowser/src/util/yyjson.h' l='5904' u='w' c='yyjson_mut_arr_with_float'/>
<use f='codebrowser/src/util/yyjson.h' l='5799' u='w' c='yyjson_mut_arr_with_double'/>
<use f='codebrowser/src/util/yyjson.h' l='5912' u='w' c='yyjson_mut_arr_with_double'/>
<use f='codebrowser/src/util/yyjson.h' l='5799' u='w' c='yyjson_mut_arr_with_str'/>
<use f='codebrowser/src/util/yyjson.h' l='5921' u='w' c='yyjson_mut_arr_with_str'/>
<use f='codebrowser/src/util/yyjson.h' l='5799' u='w' c='yyjson_mut_arr_with_strn'/>
<use f='codebrowser/src/util/yyjson.h' l='5931' u='w' c='yyjson_mut_arr_with_strn'/>
<use f='codebrowser/src/util/yyjson.h' l='5799' u='w' c='yyjson_mut_arr_with_strcpy'/>
<use f='codebrowser/src/util/yyjson.h' l='5945' u='w' c='yyjson_mut_arr_with_strcpy'/>
<use f='codebrowser/src/util/yyjson.h' l='5799' u='w' c='yyjson_mut_arr_with_strncpy'/>
<use f='codebrowser/src/util/yyjson.h' l='5959' u='w' c='yyjson_mut_arr_with_strncpy'/>
<use f='codebrowser/src/util/yyjson.h' l='6453' u='w' c='yyjson_mut_obj'/>
<use f='codebrowser/src/util/yyjson.h' l='6467' u='w' c='yyjson_mut_obj_with_str'/>
<use f='codebrowser/src/util/yyjson.h' l='6475' u='w' c='yyjson_mut_obj_with_str'/>
<use f='codebrowser/src/util/yyjson.h' l='6476' u='w' c='yyjson_mut_obj_with_str'/>
<use f='codebrowser/src/util/yyjson.h' l='6497' u='w' c='yyjson_mut_obj_with_kv'/>
<use f='codebrowser/src/util/yyjson.h' l='6507' u='w' c='yyjson_mut_obj_with_kv'/>
<use f='codebrowser/src/util/yyjson.h' l='6508' u='w' c='yyjson_mut_obj_with_kv'/>
<use f='codebrowser/src/util/yyjson.h' l='6585' u='w' c='unsafe_yyjson_mut_obj_replace'/>
<use f='codebrowser/src/util/yyjson.h' l='6585' u='r' c='unsafe_yyjson_mut_obj_replace'/>
<use f='codebrowser/src/util/yyjson.h' l='6730' u='w' c='yyjson_mut_obj_add_null'/>
<use f='codebrowser/src/util/yyjson.h' l='6731' u='w' c='yyjson_mut_obj_add_null'/>
<use f='codebrowser/src/util/yyjson.h' l='6732' u='w' c='yyjson_mut_obj_add_null'/>
<use f='codebrowser/src/util/yyjson.h' l='6745' u='w' c='yyjson_mut_obj_add_null'/>
<use f='codebrowser/src/util/yyjson.h' l='6730' u='w' c='yyjson_mut_obj_add_true'/>
<use f='codebrowser/src/util/yyjson.h' l='6731' u='w' c='yyjson_mut_obj_add_true'/>
<use f='codebrowser/src/util/yyjson.h' l='6732' u='w' c='yyjson_mut_obj_add_true'/>
<use f='codebrowser/src/util/yyjson.h' l='6753' u='w' c='yyjson_mut_obj_add_true'/>
<use f='codebrowser/src/util/yyjson.h' l='6730' u='w' c='yyjson_mut_obj_add_false'/>
<use f='codebrowser/src/util/yyjson.h' l='6731' u='w' c='yyjson_mut_obj_add_false'/>
<use f='codebrowser/src/util/yyjson.h' l='6732' u='w' c='yyjson_mut_obj_add_false'/>
<use f='codebrowser/src/util/yyjson.h' l='6761' u='w' c='yyjson_mut_obj_add_false'/>
<use f='codebrowser/src/util/yyjson.h' l='6730' u='w' c='yyjson_mut_obj_add_bool'/>
<use f='codebrowser/src/util/yyjson.h' l='6731' u='w' c='yyjson_mut_obj_add_bool'/>
<use f='codebrowser/src/util/yyjson.h' l='6732' u='w' c='yyjson_mut_obj_add_bool'/>
<use f='codebrowser/src/util/yyjson.h' l='6770' u='w' c='yyjson_mut_obj_add_bool'/>
<use f='codebrowser/src/util/yyjson.h' l='6730' u='w' c='yyjson_mut_obj_add_uint'/>
<use f='codebrowser/src/util/yyjson.h' l='6731' u='w' c='yyjson_mut_obj_add_uint'/>
<use f='codebrowser/src/util/yyjson.h' l='6732' u='w' c='yyjson_mut_obj_add_uint'/>
<use f='codebrowser/src/util/yyjson.h' l='6779' u='w' c='yyjson_mut_obj_add_uint'/>
<use f='codebrowser/src/util/yyjson.h' l='6730' u='w' c='yyjson_mut_obj_add_sint'/>
<use f='codebrowser/src/util/yyjson.h' l='6731' u='w' c='yyjson_mut_obj_add_sint'/>
<use f='codebrowser/src/util/yyjson.h' l='6732' u='w' c='yyjson_mut_obj_add_sint'/>
<use f='codebrowser/src/util/yyjson.h' l='6789' u='w' c='yyjson_mut_obj_add_sint'/>
<use f='codebrowser/src/util/yyjson.h' l='6730' u='w' c='yyjson_mut_obj_add_int'/>
<use f='codebrowser/src/util/yyjson.h' l='6731' u='w' c='yyjson_mut_obj_add_int'/>
<use f='codebrowser/src/util/yyjson.h' l='6732' u='w' c='yyjson_mut_obj_add_int'/>
<use f='codebrowser/src/util/yyjson.h' l='6799' u='w' c='yyjson_mut_obj_add_int'/>
<use f='codebrowser/src/util/yyjson.h' l='6730' u='w' c='yyjson_mut_obj_add_real'/>
<use f='codebrowser/src/util/yyjson.h' l='6731' u='w' c='yyjson_mut_obj_add_real'/>
<use f='codebrowser/src/util/yyjson.h' l='6732' u='w' c='yyjson_mut_obj_add_real'/>
<use f='codebrowser/src/util/yyjson.h' l='6809' u='w' c='yyjson_mut_obj_add_real'/>
<use f='codebrowser/src/util/yyjson.h' l='6730' u='w' c='yyjson_mut_obj_add_str'/>
<use f='codebrowser/src/util/yyjson.h' l='6731' u='w' c='yyjson_mut_obj_add_str'/>
<use f='codebrowser/src/util/yyjson.h' l='6732' u='w' c='yyjson_mut_obj_add_str'/>
<use f='codebrowser/src/util/yyjson.h' l='6822' u='w' c='yyjson_mut_obj_add_str'/>
<use f='codebrowser/src/util/yyjson.h' l='6823' u='w' c='yyjson_mut_obj_add_str'/>
<use f='codebrowser/src/util/yyjson.h' l='6730' u='w' c='yyjson_mut_obj_add_strn'/>
<use f='codebrowser/src/util/yyjson.h' l='6731' u='w' c='yyjson_mut_obj_add_strn'/>
<use f='codebrowser/src/util/yyjson.h' l='6732' u='w' c='yyjson_mut_obj_add_strn'/>
<use f='codebrowser/src/util/yyjson.h' l='6835' u='w' c='yyjson_mut_obj_add_strn'/>
<use f='codebrowser/src/util/yyjson.h' l='6730' u='w' c='yyjson_mut_obj_add_strcpy'/>
<use f='codebrowser/src/util/yyjson.h' l='6731' u='w' c='yyjson_mut_obj_add_strcpy'/>
<use f='codebrowser/src/util/yyjson.h' l='6732' u='w' c='yyjson_mut_obj_add_strcpy'/>
<use f='codebrowser/src/util/yyjson.h' l='6849' u='w' c='yyjson_mut_obj_add_strcpy'/>
<use f='codebrowser/src/util/yyjson.h' l='6730' u='w' c='yyjson_mut_obj_add_strncpy'/>
<use f='codebrowser/src/util/yyjson.h' l='6731' u='w' c='yyjson_mut_obj_add_strncpy'/>
<use f='codebrowser/src/util/yyjson.h' l='6732' u='w' c='yyjson_mut_obj_add_strncpy'/>
<use f='codebrowser/src/util/yyjson.h' l='6862' u='w' c='yyjson_mut_obj_add_strncpy'/>
<use f='codebrowser/src/util/yyjson.h' l='6730' u='w' c='yyjson_mut_obj_add_val'/>
<use f='codebrowser/src/util/yyjson.h' l='6731' u='w' c='yyjson_mut_obj_add_val'/>
<use f='codebrowser/src/util/yyjson.h' l='6732' u='w' c='yyjson_mut_obj_add_val'/>
<offset>0</offset>
<doc f='codebrowser/src/util/yyjson.h' l='5154'>/**&lt; type, subtype and length */</doc>
<use f='codebrowser/src/util/yyjson.c' l='1314' u='w' c='yyjson_val_mut_copy'/>
<use f='codebrowser/src/util/yyjson.c' l='1372' u='w' c='unsafe_yyjson_mut_val_mut_copy'/>
<use f='codebrowser/src/util/yyjson.c' l='1372' u='r' c='unsafe_yyjson_mut_val_mut_copy'/>
<use f='codebrowser/src/util/yyjson.c' l='1461' u='r' c='yyjson_imut_copy'/>
<use f='codebrowser/src/util/yyjson.c' l='1469' u='r' c='yyjson_imut_copy'/>
<use f='codebrowser/src/util/yyjson.c' l='1475' u='r' c='yyjson_imut_copy'/>
<use f='codebrowser/src/util/yyjson.c' l='1653' u='r' c='unsafe_yyjson_mut_equals'/>
<use f='codebrowser/src/util/yyjson.c' l='1653' u='r' c='unsafe_yyjson_mut_equals'/>
<use f='codebrowser/src/util/yyjson.c' l='2502' u='r' c='yyjson_merge_patch'/>
<use f='codebrowser/src/util/yyjson.c' l='2553' u='w' c='yyjson_mut_merge_patch'/>
<use f='codebrowser/src/util/yyjson.c' l='2553' u='r' c='yyjson_mut_merge_patch'/>
