<dec f='codebrowser/src/util/yyjson.h' l='4392' type='uint64_t'/>
<use f='codebrowser/src/util/yyjson.h' l='4464' u='r' c='unsafe_yyjson_get_type'/>
<use f='codebrowser/src/util/yyjson.h' l='4469' u='r' c='unsafe_yyjson_get_subtype'/>
<use f='codebrowser/src/util/yyjson.h' l='4474' u='r' c='unsafe_yyjson_get_tag'/>
<use f='codebrowser/src/util/yyjson.h' l='4544' u='r' c='unsafe_yyjson_arr_is_flat'/>
<use f='codebrowser/src/util/yyjson.h' l='4600' u='r' c='unsafe_yyjson_get_len'/>
<use f='codebrowser/src/util/yyjson.h' l='4627' u='r' c='unsafe_yyjson_set_type'/>
<use f='codebrowser/src/util/yyjson.h' l='4629' u='w' c='unsafe_yyjson_set_type'/>
<use f='codebrowser/src/util/yyjson.h' l='4633' u='r' c='unsafe_yyjson_set_len'/>
<use f='codebrowser/src/util/yyjson.h' l='4635' u='w' c='unsafe_yyjson_set_len'/>
<use f='codebrowser/src/util/yyjson.h' l='4639' u='r' c='unsafe_yyjson_inc_len'/>
<use f='codebrowser/src/util/yyjson.h' l='4641' u='w' c='unsafe_yyjson_inc_len'/>
<offset>0</offset>
<doc f='codebrowser/src/util/yyjson.h' l='4392'>/**&lt; type, subtype and length */</doc>
<use f='codebrowser/src/util/yyjson.c' l='1314' u='r' c='yyjson_val_mut_copy'/>
<use f='codebrowser/src/util/yyjson.c' l='1461' u='w' c='yyjson_imut_copy'/>
<use f='codebrowser/src/util/yyjson.c' l='1469' u='w' c='yyjson_imut_copy'/>
<use f='codebrowser/src/util/yyjson.c' l='1475' u='w' c='yyjson_imut_copy'/>
<use f='codebrowser/src/util/yyjson.c' l='1598' u='r' c='unsafe_yyjson_equals'/>
<use f='codebrowser/src/util/yyjson.c' l='1598' u='r' c='unsafe_yyjson_equals'/>
<use f='codebrowser/src/util/yyjson.c' l='2502' u='w' c='yyjson_merge_patch'/>
<use f='codebrowser/src/util/yyjson.c' l='3583' u='w' c='read_true'/>
<use f='codebrowser/src/util/yyjson.c' l='3595' u='w' c='read_false'/>
<use f='codebrowser/src/util/yyjson.c' l='3607' u='w' c='read_null'/>
<use f='codebrowser/src/util/yyjson.c' l='3637' u='w' c='read_inf'/>
<use f='codebrowser/src/util/yyjson.c' l='3640' u='w' c='read_inf'/>
<use f='codebrowser/src/util/yyjson.c' l='3664' u='w' c='read_nan'/>
<use f='codebrowser/src/util/yyjson.c' l='3667' u='w' c='read_nan'/>
<use f='codebrowser/src/util/yyjson.c' l='3698' u='w' c='read_number_raw'/>
<use f='codebrowser/src/util/yyjson.c' l='3698' u='w' c='read_number_raw'/>
<use f='codebrowser/src/util/yyjson.c' l='3698' u='w' c='read_number_raw'/>
<use f='codebrowser/src/util/yyjson.c' l='3698' u='w' c='read_number_raw'/>
<use f='codebrowser/src/util/yyjson.c' l='4210' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4228' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4241' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4222' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4241' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4222' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4216' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4241' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4228' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4228' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4241' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4228' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4228' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4241' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4228' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4222' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4228' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4241' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4228' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4228' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4241' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4228' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='4228' u='w' c='read_number'/>
<use f='codebrowser/src/util/yyjson.c' l='5202' u='w' c='read_string'/>
<use f='codebrowser/src/util/yyjson.c' l='5297' u='w' c='read_string'/>
<use f='codebrowser/src/util/yyjson.c' l='5666' u='w' c='read_root_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='5670' u='w' c='read_root_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='5677' u='w' c='read_root_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='5678' u='r' c='read_root_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='5682' u='w' c='read_root_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='5780' u='w' c='read_root_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='5785' u='r' c='read_root_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='5786' u='r' c='read_root_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='5794' u='w' c='read_root_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='5795' u='r' c='read_root_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='5797' u='w' c='read_root_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='5925' u='w' c='read_root_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='5928' u='r' c='read_root_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='5929' u='r' c='read_root_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='6056' u='w' c='read_root_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='6061' u='w' c='read_root_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='6069' u='w' c='read_root_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='6070' u='r' c='read_root_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='6074' u='w' c='read_root_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='6189' u='w' c='read_root_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='6194' u='r' c='read_root_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='6196' u='r' c='read_root_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='6204' u='w' c='read_root_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='6205' u='r' c='read_root_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='6207' u='w' c='read_root_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='6355' u='w' c='read_root_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='6358' u='r' c='read_root_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='6360' u='r' c='read_root_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='7381' u='r' c='write_number'/>
<use f='codebrowser/src/util/yyjson.c' l='7387' u='r' c='write_number'/>
