<dec f='codebrowser/src/util/yyjson.h' l='1058' type='const char *'/>
<offset>64</offset>
<doc f='codebrowser/src/util/yyjson.h' l='1057'>/** Error message, constant, no need to free (NULL if success). */</doc>
<use f='codebrowser/src/util/yyjson.c' l='8004' u='w' c='write_dat_to_fp'/>
<use f='codebrowser/src/util/yyjson.c' l='8016' u='w' c='write_dat_to_file'/>
<use f='codebrowser/src/util/yyjson.c' l='8016' u='w' c='write_dat_to_file'/>
<use f='codebrowser/src/util/yyjson.c' l='8016' u='w' c='write_dat_to_file'/>
<use f='codebrowser/src/util/yyjson.c' l='8071' u='w' c='yyjson_write_single'/>
<use f='codebrowser/src/util/yyjson.c' l='8071' u='w' c='yyjson_write_single'/>
<use f='codebrowser/src/util/yyjson.c' l='8071' u='w' c='yyjson_write_single'/>
<use f='codebrowser/src/util/yyjson.c' l='8071' u='w' c='yyjson_write_single'/>
<use f='codebrowser/src/util/yyjson.c' l='8178' u='w' c='yyjson_write_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='8178' u='w' c='yyjson_write_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='8178' u='w' c='yyjson_write_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='8178' u='w' c='yyjson_write_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='8355' u='w' c='yyjson_write_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='8355' u='w' c='yyjson_write_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='8355' u='w' c='yyjson_write_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='8355' u='w' c='yyjson_write_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='8566' u='w' c='yyjson_val_write_opts'/>
<use f='codebrowser/src/util/yyjson.c' l='8603' u='w' c='yyjson_val_write_file'/>
<use f='codebrowser/src/util/yyjson.c' l='8629' u='w' c='yyjson_val_write_fp'/>
<use f='codebrowser/src/util/yyjson.c' l='8876' u='w' c='yyjson_mut_write_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='8722' u='w' c='yyjson_mut_write_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='8722' u='w' c='yyjson_mut_write_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='8722' u='w' c='yyjson_mut_write_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='8722' u='w' c='yyjson_mut_write_minify'/>
<use f='codebrowser/src/util/yyjson.c' l='9084' u='w' c='yyjson_mut_write_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='8905' u='w' c='yyjson_mut_write_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='8905' u='w' c='yyjson_mut_write_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='8905' u='w' c='yyjson_mut_write_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='8905' u='w' c='yyjson_mut_write_pretty'/>
<use f='codebrowser/src/util/yyjson.c' l='9122' u='w' c='yyjson_mut_write_opts_impl'/>
<use f='codebrowser/src/util/yyjson.c' l='9178' u='w' c='yyjson_mut_val_write_file'/>
<use f='codebrowser/src/util/yyjson.c' l='9204' u='w' c='yyjson_mut_val_write_fp'/>
